version: '3.8'

services:
  pixelab:
    build: .
    container_name: pixelab_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    restart: unless-stopped
